### ISSUE TITLE
Syntax error while compiling on mac

### ISSUE THREAD

**Issue by thewanderer1** [PascalCoinDev/PascalCoin#69]
I attempted to compile using Lazarus 1.8.0 on my mac and I got the following syntax errors. 

`ULog.pas(162,101) Error: Incompatible type for arg no. 1: Got "TThreadID", expected "QWord"
ULog.pas(166,67) Error: Incompatible types: got "TThreadID" expected "LongWord"
ULog.pas(173,28) Error: Incompatible types: got "TThreadID" expected "LongWord"`

See the bottom left of the attached screenshot.
![screen shot 2018-01-08 at 2 01 16 pm](https://user-images.githubusercontent.com/8338136/34687528-f3917e24-f47c-11e7-8645-800478e2a1e3.png)

**Comment by SkybuckFlying** [comment]
My guess is you are trying to compile PascalCoin with a 64 bit Free Pascal compiler/Lazarus edition.

Try using a 32 bit Free Pascal compiler/Lazarus edition.

**Comment by Coldzer0** [comment]
it's not compatible with Mac OS i already fix these errors and edit some code but i didn't know what to do next

it always says Alone in the world :D 

[http://prntscr.com/i2zp5l](url)

**Comment by HermanSchoenfeld** [comment]
We’re working on os x for next release.

**Comment by Coldzer0** [comment]
@HermanSchoenfeld 
i already make it work after i download the BlockChain , but i got a lot of "Connection timed out"
but it as first try to make it work on Mac OS , it works :D 

i change the compiler directives to support Mac on FPC (i use CodeTyphon to compile)
i add libcrypto.dylib to the loading libs inside the UOpenSSL.pas and i edit some {$IFDEF LINUX}
to support Darwin (Mac)

https://youtu.be/sg2UomYZeko

maybe you guys know why this "Connection timed out" happen :D

**Comment by Esqarrouth** [comment]
What can I do to help out with testing on mac?

**Comment by PascalCoinDev** [comment]
Hi. This issue is perhaps outdated... can someone check again on Mac and tell results?

Note: I've no MAC to check...
